#define UNIATA_VER_STR         "48"
#define UNIATA_VER_DOT         0.48.0.0
#define UNIATA_VER_MJ          0
#define UNIATA_VER_MN          48
#define UNIATA_VER_SUB_MJ      0
#define UNIATA_VER_SUB_MN      0
#define UNIATA_VER_DOT_COMMA   0,48,0,0
#define UNIATA_VER_DOT_STR     "0.48.0.0"
#define UNIATA_VER_YEAR        2026
#define UNIATA_VER_YEAR_STR    "2026"
